Topic.0718.fixes v2
chflood/jigawatts pull request #31
Opened 2022-07-18 13:11 UTC by galderz

Contains a couple of fixes:

First it fixes process builder output in tests to show errors, otherwise reasons for test failures are not shown.

Second, I'm seeing some random failures like:
```
Process Process[pid=5119, exitValue=0] has leading size 12
Process Process[pid=5118, exitValue=0] has leading size 12
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 14.029 s <<< FAILURE! - in TestHooks
[ERROR] TestHooks.TestOne(Path)  Time elapsed: 14.028 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
	at TestHooks.TestOne(TestHooks.java:118)
```

The `trees` value is not used, so it could be dead code eliminated. Using the value seems to be enough to avoid DCE and get the GC logic working as the test expects. It might not be failproof but seems to work for now. On my server this was failing every other run.

2022-07-18 13:16 UTC, judovana commented on src/test/java/com/redhat/jigawatts/RandomTest.java
> -	while ((l = output.readLine()) != null) {
wouldn't best be to read both sreams?

2022-07-18 13:23 UTC, judovana commented on src/test/java/com/redhat/jigawatts/TestHooks.java
> +		System.out.println(" ");
prackets

2022-07-18 13:26 UTC, judovana requested changes
thanx a lot. 2x missing brackets, and I'm hesitating with stdout x err, as I see the tests pass consistently. wdyt about siggestion of reading both, even if async reading can be needed?

2022-07-25 10:43 UTC, galderz commented on src/test/java/com/redhat/jigawatts/RandomTest.java
> -	while ((l = output.readLine()) != null) {
What do you mean? Read both streams in a single loop? Wouldn't that get confusing if you're interleaving output and error lines?

2022-07-25 10:47 UTC, galderz commented on src/test/java/com/redhat/jigawatts/TestHooks.java
> +			System.out.println(" ");
Brackets fine. It doesn't matter what's printed because it won't be printed, or highly unlikely.

2022-07-25 10:50 UTC, galderz commented
The reason for fixing stderr is because consuming that, I couldn't see the reason why the tests were initially failing. That reason was ` /var/lib/sss/pipes/nss`.

2022-07-25 11:02 UTC, galderz commented
E.g.

```
error line 0 = Exception in thread "main" com.redhat.jigawatts.SssPipeNssFileException: criu do not work if /var/lib/sss/pipes/nss exists. By default we throw exception, if we should try, set following variable to `ignore`. Use `force` to let us delete it and resore it afterwards. Set `fierce`, similar to force, but ignoring any exceptions;-Djigawatts.ssspipesnss/$JIGAWATTS_SSSPIPESNSS: null
error line 1 = 	at com.redhat.jigawatts.SssPipeNssFileException.closeSssNssFile(SssPipeNssFileException.java:16)
error line 2 = 	at com.redhat.jigawatts.Jigawatts.preNativeActions(Jigawatts.java:136)
error line 3 = 	at com.redhat.jigawatts.Jigawatts.saveTheWorld(Jigawatts.java:81)
error line 4 = 	at com.redhat.jigawatts.Jigawatts.saveTheWorld(Jigawatts.java:87)
error line 5 = 	at RandomTest.TestRandomCheckpoint(RandomTest.java:73)
error line 6 = 	at RandomTest.main(RandomTest.java:139)
```

2022-07-25 11:04 UTC, galderz commented
Fixed the brackets via an update to the relevant commit.

2022-07-25 12:05 UTC, judovana commented on src/test/java/com/redhat/jigawatts/TestHooks.java
> +			System.out.println(" ");
I meant more  iff () {} brackets :)
```
if (Arrays.hashCode(trees) == System.nanoTime()) {
			System.out.println(" ");
}
```

2022-07-25 12:10 UTC, judovana commented
Thax. As for the  streams, my original idea was more to have one thread launched for stderr and one for stdout, and wait for both. But I agree it may be overcompelx for the case.  WDYT?

The, /var/lib/sss/pipes/nss is troublemaker.  To have hem read both in seqence can lead to more then jsut a confusion I'm not in favour of that.

2022-07-29 05:08 UTC, galderz commented on src/test/java/com/redhat/jigawatts/TestHooks.java
> +			System.out.println(" ");
Brackets have been added now.

2022-07-29 05:10 UTC, galderz commented
> Thax. As for the streams, my original idea was more to have one thread launched for stderr and one for stdout, and wait for both. But I agree it may be overcompelx for the case. WDYT?

Ah I see what you mean now. Yeah I think it sounds a bit too complex for no specific reason. This is all done in testing so you're not worried about its performance.

> The, /var/lib/sss/pipes/nss is troublemaker. To have hem read both in seqence can lead to more then jsut a confusion I'm not in favour of that.

What is it "more" that you are worried about? We need to be clear here.

2022-07-29 13:23 UTC, judovana commented
Well  to not miss any output :)

2022-07-29 13:24 UTC, merged

2022-07-29 13:26 UTC, judovana commented
I had added you to comaintainers, so you ar enot blocked by my absence